// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vefzijutxgzdjjidijri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlZnppanV0eGd6ZGpqaWRpanJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDQyMTAsImV4cCI6MjA2NTU4MDIxMH0.agJxL4LYlKz4TtrCs5nbu72zR55gY-_fgVIEXeCE84E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);