// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcvhmxcswpbeetxjgmsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjdmhteGNzd3BiZWV0eGpnbXNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjE5MDksImV4cCI6MjA2MzQ5NzkwOX0.5Bb_rLUbyS5dNhJASZGmnIs64it33aK1Z7RyH6vEzSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);